on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: pauldruziak/move-labeled-or-milestoned-pull-request@v1.0.2
      with:
        action-token: "${{ secrets.PROJECT_AUTOMATION }}"
        project-url: "https://github.com/orgs/epsilonit/projects/1"
        column-name: "In Progress"
        label-name: "bug"
