name: Adds all issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/epsilonit/projects/1
          github-token: ${{ secrets.PROJECT_AUTOMATION }}

  add-to-private-project:
    name: Add issue to private project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/epsilonit/projects/3
          github-token: ${{ secrets.PROJECT_AUTOMATION }}
